### PR TITLE
Smashing magazine heatmap

### PR DESCRIPTION
**Pull request by ArreyTabe**
In this project,  we were tasked to create a heatmap for the Smashing Magazine Website, using frontend technologies like flexbox, grid, and float.
The project has the following features:

- Nav bar with nav list items as blocks.
- Main section with flex and grids as blocks
- footer with footer nav list items and footer nav links all as blocks.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [x] Please remove the linter error.

- [x] Remove commented code

- [x] Please add all assets and styling files in a single folder.

- [x] Please add extra content like vscode to gitignore. 
- [x] Remove cursor: pointer and use an anchor tag instead of link elements.
- [x] Please add proper contact links in the readme.

- [x] In about section, please add some description of technologies and techniques you used to build this project. 
**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by arslanbisharat** [comment]
Hello,
As requested before, Please remove the linter errors

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
Hello,
As requested before, Please remove the linter errors

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great job working on the previously required changes.

## Required Changes
### [Mandatory] :red_circle: 
- [x] License link is broken in README

- [x] Elements in the footer should be links like the project does on the navbar.
image

- [x] Remove commented code
image

- [x] Remove ```cursor: pointer``` and use an anchor tag instead of link elements.

- [ ] Add to .gitigore all unnecessary files. Only push production-ready files to the repository on GitHub.
image

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by arslanbisharat — APPROVED** [review]
Congratulations Approved 🎉
Hello Developer 👋
You are on 🔥
Thank you so much for making those changes and I am very happy to approve the project. You have done a great job. 👏
Please keep working hard and move forward with your curriculum.
Looking forward to seeing your next project. 😄
---------------------------------------------------------------------------------------------------------------
**To highlight**
- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

**Pull request merged**
